//! Certified Exporter — 監査レポート生成
//! 
//! # 憲法遵守
//! - .dirtyrack.cert から人間が読める美しい HTML レポートを生成。
//! - 証拠写真（パッチ画像）や波形統計を含める。

use std::fs::File;
use std::io::Write;
use std::path::Path;

pub fn generate_html_report(cert_path: &Path) -> Result<String, String> {
    let json_str = std::fs::read_to_string(cert_path).map_err(|e| e.to_string())?;
    let cert: serde_json::Value = serde_json::from_str(&json_str).map_err(|e| e.to_string())?;
    
    let render_id = cert_path.file_stem().unwrap().to_str().unwrap();
    let report_path = cert_path.with_extension("audit.html");
    
    let mut html = String::new();
    html.push_str("<!DOCTYPE html><html><head>");
    html.push_str("<title>DirtyRack Audit Report</title>");
    html.push_str("<style>");
    html.push_str("body { background: #1a1a1a; color: #eee; font-family: sans-serif; padding: 40px; }");
    html.push_str(".cert { border: 2px solid #00aaff; padding: 20px; border-radius: 8px; background: #222; }");
    html.push_str(".hash { font-family: monospace; color: #00ffaa; word-break: break-all; }");
    html.push_str("h1 { color: #00aaff; }");
    html.push_str(".meta { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin: 20px 0; }");
    html.push_str(".status { background: #004400; color: #00ff00; padding: 5px 10px; border-radius: 4px; display: inline-block; font-weight: bold; }");
    html.push_str("</style></head><body>");
    
    html.push_str(&format!("<h1>DirtyRack Certified Render Report</h1>"));
    html.push_str(&format!("<div class='status'>{}</div>", cert["status"].as_str().unwrap_or("UNKNOWN")));
    
    html.push_str("<div class='cert'>");
    html.push_str(&format!("<h3>Render ID: {}</h3>", render_id));
    html.push_str("<div class='meta'>");
    html.push_str(&format!("<div><strong>Sample Rate:</strong> {} Hz</div>", cert["sample_rate"]));
    html.push_str(&format!("<div><strong>Engine Version:</strong> {}</div>", cert["engine_version"].as_str().unwrap_or("N/A")));
    html.push_str(&format!("<div><strong>Project Seed:</strong> {}</div>", cert["seed"]));
    html.push_str(&format!("<div><strong>Patch Hash:</strong> <span class='hash'>{}</span></div>", cert["patch_hash"].as_str().unwrap_or("N/A")));
    html.push_str("</div>");
    
    html.push_str("<h4>Cryptographic Evidence</h4>");
    html.push_str(&format!("<p>The following BLAKE3 hash uniquely identifies the audio bitstream produced by this render. Any modification to the audio will invalidate this certificate.</p>"));
    html.push_str(&format!("<div class='hash'>{}</div>", cert["render_hash"].as_str().unwrap_or("N/A")));
    html.push_str("</div>");
    
    html.push_str("<p style='margin-top:40px; opacity:0.5;'>Generated by DirtyRack Forensic Suite — Audit & Truth.</p>");
    html.push_str("</body></html>");
    
    let mut f = File::create(&report_path).map_err(|e| e.to_string())?;
    f.write_all(html.as_bytes()).map_err(|e| e.to_string())?;
    
    Ok(report_path.to_string_lossy().to_string())
}
